name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: deep-sun-444206-n0

    - name: Build React
      run: |
        cd my-app
        npm install
        npm run build

    - name: Copy React build to Spring Boot
      run: |
        cp -r my-app/build/* backend/src/main/resources/static/

    - name: Build and Run Spring Boot
      run: |
        cd backend
        ./gradlew clean build --refresh-dependencies
        ./gradlew bootrun
