name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Change directory to my-app
      run: cd my-app

    - name: Install dependencies
      run: npm install
      working-directory: ./my-app

    - name: Build the project
      run: npm run build
      working-directory: ./my-app

    - name: Deploy to GitHub Pages
      run: npm run deploy
      working-directory: ./my-app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
